'use client';

import React from 'react';
import MainLayout from '@/components/MainLayout';
import PageLayout from '@/components/PageLayout';
import styles from './Disclaimer.module.css';

const Disclaimer = () => {
  return (
    <MainLayout>
      <PageLayout 
        title="Disclaimer" 
        subtitle="Important information about using our AI services"
      >
        <div className={styles.disclaimerContent}>
          <section className={styles.section}>
            <h2>AI Generated Content Disclaimer</h2>
            <p>
              The content generated by our AI tools is for informational purposes only. While we strive
              for accuracy and reliability, we cannot guarantee that the AI-generated content will be
              error-free or suitable for any particular purpose.
            </p>
          </section>

          <section className={styles.section}>
            <h2>No Professional Advice</h2>
            <p>
              Our AI tools do not provide professional, legal, medical, or financial advice. The
              information provided should not be used as a substitute for professional consultation.
              Always seek the advice of qualified professionals for specific situations.
            </p>
            <ul>
              <li>Do not rely on AI for medical diagnoses or treatment</li>
              <li>Do not use AI-generated content for legal documents without professional review</li>
              <li>Verify any financial or business advice with qualified professionals</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>Accuracy and Reliability</h2>
            <p>
              While our AI models are trained on extensive data, they may occasionally:
            </p>
            <ul>
              <li>Generate inaccurate or outdated information</li>
              <li>Provide incomplete or biased responses</li>
              <li>Misinterpret context or nuance</li>
              <li>Make mistakes in calculations or facts</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>User Responsibility</h2>
            <p>
              Users are responsible for:
            </p>
            <ul>
              <li>Verifying AI-generated information before use</li>
              <li>Using the services in compliance with applicable laws</li>
              <li>Ensuring appropriate use of AI-generated content</li>
              <li>Maintaining privacy and security of their information</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2>Limitation of Liability</h2>
            <p>
              AI Chat Tools and its operators are not liable for any damages or losses resulting from
              the use of our AI services, including but not limited to:
            </p>
            <ul>
              <li>Direct or indirect financial losses</li>
              <li>Business interruption</li>
              <li>Loss of data or information</li>
              <li>Decisions made based on AI-generated content</li>
            </ul>
          </section>

          <div className={styles.callout}>
            <i className="fas fa-exclamation-circle"></i>
            <p>
              By using our AI tools, you acknowledge and agree to these disclaimers. If you do not
              agree, please discontinue use of our services.
            </p>
          </div>
        </div>
      </PageLayout>
    </MainLayout>
  );
};

export default Disclaimer; 